// src/core/JSONTracker_Migrator.js

import { getDefaultCharacters } from './PromptSchema.js';

/**
 * Generate a unique ID combining timestamp and random string
 */
export function generateUniqueId(prefix) {
    const randomSuffix = Math.random().toString(36).substring(2, 7);
    return `${prefix}_${Date.now()}_${randomSuffix}`;
}

/**
 * Sanitize name string into a valid safe ID format
 */
export function cleanIdString(name, prefix) {
    if (!name) return generateUniqueId(prefix);
    const clean = name.replace(/[^\p{L}\p{N}_]/gu, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
    return clean ? `${prefix}_${clean}` : generateUniqueId(prefix);
}

/**
 * Parse metadata format generated by the LLM (value, type, min, max)
 */
export function parseMetadata(rawVal) {
    if (typeof rawVal !== 'string') return { value: rawVal, type: null, min: null, max: null };
    const metaMatch = rawVal.match(/^(.*?)\s*\(\s*type:\s*([a-zA-Z_]+)(?:[^)]*?min:\s*(-?\d+))?(?:[^)]*?max:\s*(-?\d+))?.*?\)$/i);
    if (metaMatch) {
        return {
            value: metaMatch[1].trim(),
            type: metaMatch[2].toLowerCase(),
            min: metaMatch[3] ? parseInt(metaMatch[3], 10) : null,
            max: metaMatch[4] ? parseInt(metaMatch[4], 10) : null
        };
    }
    return { value: rawVal, type: null, min: null, max: null };
}

/**
 * Migrate legacy nested character features data into a flat schema
 */
export function migrateCharacterSchema(char) {
    if (char && char.featuresData) {
        const { profile, profileLocks, profileInjects, inventory, quests } = char.featuresData;
        const migrated = {
            ...char,
            profile: profile || char.profile || { Race: '', Height: '', Appearance: '' },
            profileLocks: profileLocks || char.profileLocks || { Race: false, Height: false, Appearance: false },
            profileInjects: profileInjects || char.profileInjects || {},
            inventory: inventory || char.inventory || {
                equipIsLocked: false,
                equipIsInject: true,
                storageIsLocked: false,
                storageIsInject: true,
                equipmentLocks: {},
                storageLocks: {},
                equipment: { 'Right Hand': null, 'Left Hand': null },
                storage: { 'Backpack': [] }
            },
            quests: quests || char.quests || { main: { name: '', desc: '' }, sides: [] }
        };
        delete migrated.featuresData;
        return migrated;
    }

    // 구버전 세이브 파일 로딩 시 인벤토리 하위의 미세 제어 자물쇠 객체 부재 대응
    if (char && char.inventory) {
        if (!char.inventory.equipmentLocks) {
            char.inventory.equipmentLocks = {};
        }
        if (!char.inventory.storageLocks) {
            char.inventory.storageLocks = {};
        }
    }

    return char;
}

/**
 * Sanitize, clean and migrate legacy tracker structures and handle internal mappings
 */
export function sanitizeTrackerData(trackerData) {
    if (!trackerData) return trackerData;

    const data = trackerData;
    const nextGlobalDefs = data.globalDefinitions ? { ...data.globalDefinitions } : null;

    if (Array.isArray(data.characters)) {
        data.characters.forEach((char, idx) => {
            char = migrateCharacterSchema(char);
            data.characters[idx] = char;

            if (char.name && char.name.trim() !== '') {
                const targetCharId = char.id === 'char_user' && char.name === 'New' ? 'char_user' : cleanIdString(char.name, 'char');
                if (char.id !== targetCharId) {
                    char.id = targetCharId;
                }
            }

            if (char.statsSchema && !char.statusSchema) {
                char.statusSchema = char.statsSchema;
                delete char.statsSchema;
            }
            if (char.stats && !char.status) {
                char.status = char.stats;
                delete char.stats;
            }

            const nextStatus = {};
            const schemaIdMapping = {};

            if (Array.isArray(char.statusSchema)) {
                char.statusSchema.forEach(schema => {
                    const oldId = schema.id;
                    if (schema.name && schema.name.trim() !== '') {
                        const cleanId = schema.name.replace(/[^\p{L}\p{N}_]/gu, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '');
                        const newId = cleanId || generateUniqueId('status');

                        if (!oldId || oldId !== newId) {
                            schema.id = newId;
                            if (oldId) {
                                schemaIdMapping[oldId] = newId;
                            }
                        }

                        const lowerName = schema.name.trim().toLowerCase();
                        schemaIdMapping[`stat_${lowerName}`] = newId;
                        schemaIdMapping[`status_${lowerName}`] = newId;

                        if (nextGlobalDefs && oldId) {
                            const legacyGuideId1 = oldId;
                            const legacyGuideId2 = `stat_${cleanId}`;
                            const newGuideId = `status_${cleanId}`;

                            const guideVal = nextGlobalDefs[legacyGuideId1] !== undefined ? nextGlobalDefs[legacyGuideId1] : nextGlobalDefs[legacyGuideId2];
                            if (guideVal !== undefined) {
                                nextGlobalDefs[newGuideId] = guideVal;
                                if (legacyGuideId1 !== newGuideId) delete nextGlobalDefs[legacyGuideId1];
                                if (legacyGuideId2 !== newGuideId) delete nextGlobalDefs[legacyGuideId2];
                            }
                        }
                    } else if (schema.id && !schema.name) {
                        schema.name = schema.id;
                    } else if (!schema.id && !schema.name) {
                        schema.id = generateUniqueId('status');
                        schema.name = schema.id;
                    }
                });
            }

            if (char.status) {
                Object.entries(char.status).forEach(([key, val]) => {
                    let cleanVal = val;
                    if (typeof val === 'string' && val.includes('(type:')) {
                        const meta = parseMetadata(val);
                        const parsedInt = parseInt(meta.value, 10);
                        cleanVal = !isNaN(parsedInt) ? parsedInt : meta.value;
                    }
                    const targetId = schemaIdMapping[key] || key;
                    nextStatus[targetId] = cleanVal;
                });
                char.status = nextStatus;
            }
        });
    }

    if (nextGlobalDefs) {
        data.globalDefinitions = nextGlobalDefs;
    }

    return data;
}