import React, { useState, useEffect, useMemo } from 'react';
import { useRPG } from '../core/RPGControl';
import styles from './SnapshotModal.module.css';
import { buildSnapshotPayload, generateSnapshotTag } from './SnapshotCore';

export default function SnapshotModal() {
  const { trackerData, snapshotModalData } = useRPG();

  const [selections, setSelections] = useState({
    world: { selected: false, date: true, time: true, weather: true, location: true, events: false },
    chars: {}
  });
  const [customNote, setCustomNote] = useState('');

  const [isEditable, setIsEditable] = useState(false);
  const [jsonText, setJsonText] = useState('{}');

  const targetData = snapshotModalData?.historicalData || trackerData;

  useEffect(() => {
    if (snapshotModalData?.isOpen && targetData.characters) {
      const initChars = {};
      targetData.characters.forEach(c => {
        initChars[c.id] = { selected: false, status: false, profile: false, relations: false, inventory: false, quests: false };
      });

      let initWorld = { selected: false, date: true, time: true, weather: true, location: true, events: false };
      let initNote = '';

      const ep = snapshotModalData.existingPayload;
      if (ep) {
        if (ep.note) initNote = ep.note;
        if (ep.world) {
          initWorld = {
            selected: true,
            date: ep.world.date !== undefined,
            time: ep.world.time !== undefined,
            weather: ep.world.weather !== undefined,
            location: ep.world.location !== undefined,
            events: ep.world.events !== undefined
          };
        }
        if (ep.chars) {
          Object.entries(ep.chars).forEach(([cName, cData]) => {
            const charObj = targetData.characters.find(c => c.name === cName);
            if (charObj) {
              initChars[charObj.id] = {
                selected: true,
                status: !!cData.status,
                profile: !!cData.profile,
                relations: !!cData.relations,
                inventory: !!cData.inventory,
                quests: !!cData.quests
              };
            }
          });
        }
      }

      setSelections({ world: initWorld, chars: initChars });
      setCustomNote(initNote);
      setIsEditable(false);
    }
  }, [snapshotModalData?.isOpen, targetData, snapshotModalData?.existingPayload]);

  const autoGeneratedPayload = useMemo(() => {
    return buildSnapshotPayload(targetData, selections, customNote);
  }, [targetData, selections, customNote]);

  useEffect(() => {
    if (!isEditable) {
      setJsonText(JSON.stringify(autoGeneratedPayload, null, 2) || '{}');
    }
  }, [autoGeneratedPayload, isEditable]);

  if (!snapshotModalData?.isOpen) return null;

  const handleClose = () => {
    if (window.RPGBridge) window.RPGBridge.closeSnapshotModal();
  };

  const handleDeselectAll = () => {
    const resetChars = {};
    if (targetData.characters) {
      targetData.characters.forEach(c => {
        resetChars[c.id] = { selected: false, status: false, profile: false, relations: false, inventory: false, quests: false };
      });
    }

    setSelections({
      world: { selected: false, date: false, time: false, weather: false, location: false, events: false },
      chars: resetChars
    });
    setCustomNote('');
  };

  const handleWorldToggle = (field, checked) => {
    setSelections(prev => {
      const worldSel = prev.world || { selected: false, date: true, time: true, weather: true, location: true, events: false };
      return {
        ...prev,
        world: {
          ...worldSel,
          [field]: checked
        }
      };
    });
  };

  const handleCharToggle = (charId, field, checked) => {
    setSelections(prev => {
      const charSel = prev.chars[charId] || { selected: false, status: false, profile: false, relations: false, inventory: false, quests: false };

      if (field === 'selected' && checked) {
        return {
          ...prev,
          chars: {
            ...prev.chars,
            [charId]: { ...charSel, selected: true, status: true, profile: true, relations: true }
          }
        };
      }

      return {
        ...prev,
        chars: {
          ...prev.chars,
          [charId]: { ...charSel, [field]: checked }
        }
      };
    });
  };

  const handleAttach = () => {
    const context = window.SillyTavern?.getContext?.();
    if (!context || !context.chat) return;

    let finalPayload;
    try {
      finalPayload = JSON.parse(jsonText);
    } catch (e) {
      alert("Invalid JSON format! Please correct the syntax before saving.");
      return;
    }

    const mesId = parseInt(snapshotModalData.mesId, 10);
    const targetMsg = context.chat.find(m => String(m.mesId) === String(mesId) || String(context.chat.indexOf(m)) === String(mesId));

    if (!targetMsg) return;

    const rpgmtRegex = /(?:\n\n)?(?:<!--\s*)?(?:(?:<|&lt;)rpgmt(?:>|&gt;)|<div class="rpgmt-data">)[\s\S]*?(?:(?:<|&lt;)\/rpgmt(?:>|&gt;)|<\/div>)(?:\s*-->)?/gi;

    if (Object.keys(finalPayload).length === 0) {
      targetMsg.mes = targetMsg.mes.replace(rpgmtRegex, '').trim();
    } else {
      const newTag = generateSnapshotTag(finalPayload);
      if (rpgmtRegex.test(targetMsg.mes)) {
        targetMsg.mes = targetMsg.mes.replace(new RegExp(rpgmtRegex.source, 'i'), newTag);
      } else {
        targetMsg.mes += newTag;
      }
    }

    let swipeId = targetMsg.swipe_id || 0;
    if (targetMsg.swipes && targetMsg.swipes.length > 0 && typeof targetMsg.mes === 'string') {
      const foundIdx = targetMsg.swipes.findIndex(s => s === targetMsg.mes);
      if (foundIdx !== -1) swipeId = foundIdx;
    }

    if (targetMsg.swipe_info && targetMsg.swipe_info[swipeId]?.extra?.rpgTrackerData) {
      const histData = targetMsg.swipe_info[swipeId].extra.rpgTrackerData;

      if (finalPayload.world && histData.worldState) {
        Object.assign(histData.worldState, finalPayload.world);
      }
      if (finalPayload.chars && histData.characters) {
        Object.entries(finalPayload.chars).forEach(([cName, cEdits]) => {
          const charObj = histData.characters.find(c => c.name === cName);
          if (charObj) {
            if (cEdits.status) Object.assign(charObj.status, cEdits.status);
            if (cEdits.profile) Object.assign(charObj.profile, cEdits.profile);
            if (cEdits.relations) {
              charObj.relations = { ...(charObj.relations || {}), ...cEdits.relations };
            }
            if (cEdits.inventory) {
              charObj.inventory = {
                ...charObj.inventory,
                equipment: { ...(charObj.inventory?.equipment || {}), ...(cEdits.inventory.equipment || {}) },
                storage: { ...(charObj.inventory?.storage || {}), ...(cEdits.inventory.storage || {}) }
              };
            }
            if (cEdits.quests) {
              charObj.quests = {
                ...charObj.quests,
                main: cEdits.quests.main !== undefined ? cEdits.quests.main : charObj.quests?.main,
                sides: cEdits.quests.sides !== undefined ? cEdits.quests.sides : charObj.quests?.sides
              };
            }
          }
        });
      }
    }

    const msgIndex = context.chat.indexOf(targetMsg);

    if (window.RPGBridge) {
      if (typeof window.RPGBridge.updateMessageBlock === 'function') {
        window.RPGBridge.updateMessageBlock(msgIndex, targetMsg);
      }
      if (typeof window.RPGBridge.saveChat === 'function') {
        window.RPGBridge.saveChat();
      }
      if (typeof window.RPGBridge.triggerSnapshotRender === 'function') {
        window.RPGBridge.triggerSnapshotRender();
      }
    }

    handleClose();
  };

  const isHistorical = !!snapshotModalData.historicalData;

  return (
    <div className={styles.overlay}>
      <div className={styles.modal} onClick={e => e.stopPropagation()}>
        <header className={styles.header}>
          <h4>Message Tracker</h4>
          <button className={styles.closeBtn} onClick={handleClose}>×</button>
        </header>

        <div className={styles.body}>
          <div style={{ fontSize: '11px', color: isHistorical ? '#2ecc71' : '#f39c12' }}>
            {isHistorical
              ? "✓ Loaded historical state from this turn."
              : "⚠️ No historical data found. Using current live data."}
          </div>

          <div className={styles.section}>
            <div className={styles.sectionTitleRow}>
              <div className={styles.sectionTitle}>Entities & Options</div>
              <button
                type="button"
                className={styles.deselectAllBtn}
                onClick={handleDeselectAll}
                title="Deselect all elements & notes"
              >
                Deselect All
              </button>
            </div>

            <div className={`${styles.charRow} ${styles.worldRow}`}>
              <label className={styles.checkboxItem} style={{ marginTop: '2px' }}>
                <input
                  type="checkbox"
                  checked={selections.world?.selected || false}
                  onChange={e => handleWorldToggle('selected', e.target.checked)}
                />
                <span className={styles.charNameLabel}>World State</span>
              </label>

              <div className={`${styles.worldOptionsContainer} ${selections.world?.selected ? styles.activeOps : styles.disabledOps}`}>
                <div className={styles.worldOptionsRow}>
                  <label className={styles.checkboxItem}>
                    <input
                      type="checkbox"
                      disabled={!selections.world?.selected}
                      checked={selections.world?.date ?? true}
                      onChange={e => handleWorldToggle('date', e.target.checked)}
                    /> Date
                  </label>
                  <label className={styles.checkboxItem}>
                    <input
                      type="checkbox"
                      disabled={!selections.world?.selected}
                      checked={selections.world?.time ?? true}
                      onChange={e => handleWorldToggle('time', e.target.checked)}
                    /> Time
                  </label>
                  <label className={styles.checkboxItem}>
                    <input
                      type="checkbox"
                      disabled={!selections.world?.selected}
                      checked={selections.world?.weather ?? true}
                      onChange={e => handleWorldToggle('weather', e.target.checked)}
                    /> Weather
                  </label>
                </div>
                <div className={styles.worldOptionsRow}>
                  <label className={styles.checkboxItem}>
                    <input
                      type="checkbox"
                      disabled={!selections.world?.selected}
                      checked={selections.world?.location ?? true}
                      onChange={e => handleWorldToggle('location', e.target.checked)}
                    /> Location
                  </label>
                  <label className={styles.checkboxItem}>
                    <input
                      type="checkbox"
                      disabled={!selections.world?.selected}
                      checked={selections.world?.events ?? false}
                      onChange={e => handleWorldToggle('events', e.target.checked)}
                    /> Events
                  </label>
                </div>
              </div>
            </div>

            {targetData.characters?.map(char => {
              const charSel = selections.chars[char.id] || {};
              return (
                <div key={char.id} className={styles.charRow} style={{ alignItems: 'flex-start' }}>
                  <label className={styles.checkboxItem} style={{ marginTop: '4px' }}>
                    <input
                      type="checkbox"
                      checked={charSel.selected || false}
                      onChange={e => handleCharToggle(char.id, 'selected', e.target.checked)}
                    />
                    <span className={styles.charNameLabel}>{char.name}</span>
                  </label>

                  <div className={`${styles.charOptionsColumn} ${charSel.selected ? styles.activeOps : styles.disabledOps}`}>
                    <div className={styles.charOptionsRow}>
                      <label className={styles.checkboxItem}>
                        <input type="checkbox" disabled={!charSel.selected} checked={charSel.status || false} onChange={e => handleCharToggle(char.id, 'status', e.target.checked)} /> Status
                      </label>
                      <label className={styles.checkboxItem}>
                        <input type="checkbox" disabled={!charSel.selected} checked={charSel.profile || false} onChange={e => handleCharToggle(char.id, 'profile', e.target.checked)} /> Profile
                      </label>
                      <label className={styles.checkboxItem}>
                        <input type="checkbox" disabled={!charSel.selected} checked={charSel.relations || false} onChange={e => handleCharToggle(char.id, 'relations', e.target.checked)} /> Relations
                      </label>
                    </div>

                    {char.activePlayer && (
                      <div className={styles.charOptionsRow} style={{ marginTop: '6px' }}>
                        <label className={styles.checkboxItem}>
                          <input type="checkbox" disabled={!charSel.selected} checked={charSel.inventory || false} onChange={e => handleCharToggle(char.id, 'inventory', e.target.checked)} /> Inventory
                        </label>
                        <label className={styles.checkboxItem}>
                          <input type="checkbox" disabled={!charSel.selected} checked={charSel.quests || false} onChange={e => handleCharToggle(char.id, 'quests', e.target.checked)} /> Quests
                        </label>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          <div className={styles.section}>
            <div className={styles.sectionTitle}>Custom Note (Optional)</div>
            <textarea
              className={styles.textarea}
              placeholder="e.g. Received the mysterious key from the merchant."
              value={customNote}
              onChange={e => setCustomNote(e.target.value)}
              disabled={isEditable}
            />
          </div>

          <div className={styles.section}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
              <div className={styles.sectionTitle} style={{ margin: 0 }}>Preview</div>
              <button
                type="button"
                className={isEditable ? styles.viewBtnActive : styles.viewBtn}
                onClick={() => {
                  if (isEditable) {
                    try {
                      JSON.parse(jsonText);
                      setIsEditable(false);
                    } catch (err) {
                      alert("Syntax error inside JSON. Please fix it before locking.");
                    }
                  } else {
                    setIsEditable(true);
                  }
                }}
              >
                {isEditable ? '🔒 Lock Data' : '🔓 Edit JSON'}
              </button>
            </div>

            <textarea
              className={`${styles.jsonEditor} ${isEditable ? styles.jsonEditorWritable : ''}`}
              value={jsonText}
              onChange={e => {
                if (isEditable) setJsonText(e.target.value);
              }}
              readOnly={!isEditable}
              placeholder="Select entities above or click 'Edit' to enter custom JSON data..."
              spellCheck="false"
            />
          </div>
        </div>

        <footer className={styles.footer}>
          <button className={styles.cancelBtn} onClick={handleClose}>Cancel</button>
          <button className={styles.saveBtn} onClick={handleAttach}>Attach Tracker</button>
        </footer>
      </div>
    </div>
  );
}